# Generated by Django 4.1 on 2022-08-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_created_at_alter_comment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=70, null=True, verbose_name='Post slug'),
        ),
    ]
