# Generated by Django 4.1 on 2022-08-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="birthdate",),
        migrations.AlterField(
            model_name="user",
            name="image_url",
            field=models.URLField(blank=True, verbose_name="Image URL"),
        ),
    ]
